version: "3.5"

services:
  api1: &api
    image: ghcr.io/keuller/rinhabe-gleam:latest
    container_name: "rinha-api1"
    environment:
      DB_POOL: "30"
      API_PORT: 3001
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    deploy:
     resources:
       limits:
        cpus: "0.25"
        memory: "120MB"
  
  api2:
    <<: *api
    container_name: "rinha-api2"
    environment:
      DB_POOL: "30"
      API_PORT: 3002

  balancer:
    image: nginx:latest
    container_name: "rinha-slb"
    hostname: slb
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  db:
    image: postgres:16-alpine
    container_name: "rinha-db"
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    command: postgres -c shared_buffers=128MB -c fsync=off -c full_page_writes=false -c commit_delay=5000 -c work_mem=8MB -c synchronous_commit=off
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./etc/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./etc/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "500MB"
      restart_policy:
        condition: on-failure
